const fs = require('fs');
const path = require('path');

const dir = 'c:\\Users\\selva\\OneDrive\\Documents\\eThandadotcom';
const auditPath = path.join(dir, 'tech-audit.html');
let html = fs.readFileSync(auditPath, 'utf8');

const oldGridStart = html.indexOf('<div class="services-grid">');
const oldGridEnd = html.indexOf('</div>', html.lastIndexOf('</div>', html.indexOf('<section class="hero-section" style="background: white; border-top: 1px solid rgba(0,0,0,0.05);">'))); 
// Safer approach: use regex to replace the specific block between <div class="services-grid"> and its closing tag before the next section.
// Actually, let's just write a precise replacement string since it was generated by our previous script.

const newGrid = `<div class="services-grid">
      <!-- Card 1 -->
      <div class="service-card" style="border: 1px solid rgba(0,0,0,0.05); box-shadow: 0 4px 20px rgba(0,0,0,0.03);">
        <div style="background: rgba(168,85,247,0.1); width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 1.5rem;">
          <i class="fa-solid fa-scissors" style="font-size: 1.5rem; color: var(--accent-purple);"></i>
        </div>
        <h4 style="color: var(--text-primary); margin-bottom: 1rem; font-size: 1.25rem;">Software Cleanup & Cost Cutting</h4>
        <p style="color: var(--text-secondary); font-size: 0.95rem; line-height: 1.6;">Stop paying for 5 different software tools that don't talk to each other. We find the redundancies, cancel the bloated subscriptions, and connect everything into one smooth system.</p>
      </div>

      <!-- Card 2 -->
      <div class="service-card" style="border: 1px solid rgba(0,0,0,0.05); box-shadow: 0 4px 20px rgba(0,0,0,0.03);">
        <div style="background: rgba(14,165,233,0.1); width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 1.5rem;">
          <i class="fa-solid fa-comment-sms" style="font-size: 1.5rem; color: var(--accent-cyan);"></i>
        </div>
        <h4 style="color: var(--text-primary); margin-bottom: 1rem; font-size: 1.25rem;">Automated Customer Follow-Ups</h4>
        <p style="color: var(--text-secondary); font-size: 0.95rem; line-height: 1.6;">Never lose a lead to a missed call again. We build automated systems that text or email your customers the second they reach out, keeping them engaged while you focus on the job.</p>
      </div>

      <!-- Card 3 -->
      <div class="service-card" style="border: 1px solid rgba(0,0,0,0.05); box-shadow: 0 4px 20px rgba(0,0,0,0.03);">
        <div style="background: rgba(168,85,247,0.1); width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 1.5rem;">
          <i class="fa-solid fa-list-check" style="font-size: 1.5rem; color: var(--accent-purple);"></i>
        </div>
        <h4 style="color: var(--text-primary); margin-bottom: 1rem; font-size: 1.25rem;">Custom Portals & Trackers</h4>
        <p style="color: var(--text-secondary); font-size: 0.95rem; line-height: 1.6;">Tired of tracking inventory or client projects in messy Excel spreadsheets? We build custom, private web apps designed specifically for how your unique business operates.</p>
      </div>

      <!-- Card 4 -->
      <div class="service-card" style="border: 1px solid rgba(0,0,0,0.05); box-shadow: 0 4px 20px rgba(0,0,0,0.03);">
        <div style="background: rgba(14,165,233,0.1); width: 50px; height: 50px; border-radius: 12px; display: flex; align-items: center; justify-content: center; margin-bottom: 1.5rem;">
          <i class="fa-solid fa-robot" style="font-size: 1.5rem; color: var(--accent-cyan);"></i>
        </div>
        <h4 style="color: var(--text-primary); margin-bottom: 1rem; font-size: 1.25rem;">24/7 Smart Website Assistants</h4>
        <p style="color: var(--text-secondary); font-size: 0.95rem; line-height: 1.6;">We build intelligent virtual assistants for your website that actually know your business, answer client questions at 2 AM, and book appointments while you sleep.</p>
      </div>
    </div>`;

// Use regex to replace everything between <div class="services-grid"> and the end of the section container
const regex = /<div class="services-grid">[\s\S]*?<\/section>/;
html = html.replace(regex, newGrid + '\n  </section>');

fs.writeFileSync(auditPath, html);
console.log('Successfully updated tech-audit.html cards.');
